[package]
name = "compression_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "compression_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.21"
rand = "0.8"


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
